CROSSCPP=/opt/avr-gcc-4.8.2/bin/avr-g++
CROSSCC=/opt/avr-gcc-4.8.2/bin/avr-gcc

CFLAGS = -Os -DF_CPU=16000000L -DUSB_PID=NULL -DUSB_VID=NULL -DARDUINO=105 -D__AVR_ATmega2560__ -DDEBUG -Wall -fmessage-length=0 -mmcu=atmega2560 -ffunction-sections -fdata-sections -fno-exceptions
LDFLAGS = -Os -Wl,--gc-sections,--relax -mmcu=atmega2560 

DIRS = Framework Actuators Controller Sensors
DIRS += libraries/Arduino
DIRS += libraries/Ethernet libraries/Ethernet/utility
DIRS += libraries/HttpClient
DIRS += libraries/OneWire
DIRS += libraries/SD libraries/SD/utility
DIRS += libraries/SPI
DIRS += libraries/TemplateParser
DIRS += libraries/Time
DIRS += libraries/Webduino
DIRS += libraries/Xively

INC = .
INC += libraries/Arduino
INC += libraries/Ethernet libraries/Ethernet/utility
INC += libraries/HttpClient
INC += libraries/OneWire
INC += libraries/SD libraries/SD/utility
INC += libraries/SPI
INC += libraries/TemplateParser
INC += libraries/Time
INC += libraries/Webduino
INC += libraries/Xively

INC_PARAMS = $(foreach d, $(INC), -I$(PREFIX)/$d)

OBJDIR = $(PWD)/obj

$(OBJDIR)/%.o: %.cpp
	$(CROSSCPP) $(INC_PARAMS) -c -o $@ $(CFLAGS) $<
	
$(OBJDIR)/%.o: %.c
	$(CROSSCC) $(INC_PARAMS) -c -o $@ $(CFLAGS) $< 

all: $(foreach d, $(OBJS), $d.o)