hex: all
	avr-objcopy -O ihex -R .eeprom Aquaduino.elf Aquaduino.hex
	
size: all
	avr-size Aquaduino.elf

	
upload: hex
	avrdude -C..\avrdude.conf -patmega2560 -cwiring -P\\.\$(ARDUINOCOM) -b115200 -D -Uflash:w:Aquaduino.hex:i 